### ISSUE TITLE
It would be good to Include a minimal index.html file

### ISSUE THREAD

**Issue by steatopygous** [Blade67/Sveltron#1]
Hi,

First, thanks for creating this!  The old svelte + electron boilerplate created by Rich Harris hasn't been updated to work with Svelte 3, so this was very helpful.

Can I suggest that you include a **public** folder in the repo, with a minimal **index.html** file that just pulls in **bundle.js**?  Without that, **npm run dev** doesn't actually produce a working app out of the box, you just get an empty window.

It was easy for me to sort out, once I realised what the problem was, but having the **index.html** file in there already would have saved me a bit of head scratching :-).

Again, thanks for providing this as a nice starting point.

Cheers,
Harry O.

**Comment by Blade67** [comment]
Hello!
Thanks for your kind words and sorry for the delay!
Beeing fairly new to Github, I haven't noticed this issue beeing posted, and I'm glad to tell you that these changes have been made, the `index.html` and `global.css` files have been added to the `/public` folder and use relative paths.

Max
