### ISSUE TITLE
Accessing node modules

### ISSUE THREAD

**Issue by rickhall** [Blade67/Sveltron#2]
Perhaps I'm just missing the obvious, but if I want to use the node fs module, how do I go about that? If I try to import it in App.svelte, the module cannot be found. Thanks

**Comment by Blade67** [comment]
Hello, excuse the delay, I'm not as much on github as I'd like to be. 

Svelte is still a front-end framework so Svelte by itself cannot use FS. I recommend using some intermediate Rollup plugin like `rollup-plugin-replace` which would save FS values to a variable, which you could then use inside your code.

I might make an example project of that some time in the future. 

 - Blade.

**Comment by rickhall** [comment]
Thanks for the suggestion, I'll look into it and see if I can figure something out.
